Bnice/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace="core")),
    path('accounts/', include('accounts.urls', namespace="accounts")),
    path('dashboard/', include('dashboard.urls', namespace="dashboard")),
]

if settings.DEBUG:  # pragma: no cover
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

if settings.DEBUG:  # pragma: no cover
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

accounts/urls.py
from django.urls import path, re_path
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordChangeView,
    PasswordChangeDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView
)
from accounts.views import SignupPage

app_name = "accounts"

urlpatterns = [
    path('signup/', SignupPage.as_view(), name='signup'),
    path('login/', LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('password_change/', PasswordChangeView.as_view(template_name='accounts/password_change_form.html'),
         name='password_change'),
    path('password_change/done/', PasswordChangeDoneView.as_view(template_name='accounts/password_change_done.html'),
         name='password_change_done'),
    path('password_reset/', PasswordResetView.as_view(template_name='accounts/password_reset_form.html'),
         name='password_reset'),
    path('password_reset/done/', PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'),
         name='password_reset_done'),
    re_path(
        r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        PasswordResetConfirmView.as_view(template_name='accounts/password_reset_confirm.html'),
        name='password_reset_confirm'),
    path('reset/done/', PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'),
         name='password_reset_complete'),
]

core/urls.py
from django.urls import path
from core.views import HomePage

app_name = "core"


urlpatterns = [
    path('', HomePage.as_view(), name="home")
]

dashboard/urls.py
from django.urls import path
from dashboard.views import (
    DashboardPage, CreateChildPage, ChildDetail,
    AddSmiley, AddOopsy, UserUpdate, ChildUpdate, ChildDelete,
    SmileyDelete, OopsyDelete, SmileyUpdate, OopsyUpdate)

app_name = "dashboard"

urlpatterns = [
    path('', DashboardPage.as_view(), name="dashboard"),
    path('child/<int:pk>/', ChildDetail.as_view(), name="child-detail"),
    path('child/new/', CreateChildPage.as_view(), name="child-create"),
    path('child/<int:pk>/edit/', ChildUpdate.as_view(), name="child-update"),
    path('child/<int:pk>/delete/', ChildDelete.as_view(), name='child-delete'),
    path('child/<int:pk>/smiley/new/', AddSmiley.as_view(), name="smiley-create"),
    path('child/<int:child_pk>/smiley/<int:pk>/delete/', SmileyDelete.as_view(), name='smiley-delete'),
    path('child/<int:child_pk>/smiley/<int:pk>/edit/', SmileyUpdate.as_view(), name='smiley-update'),
    path('child/<int:pk>/oopsy/new/', AddOopsy.as_view(), name="oopsy-create"),
    path('child/<int:child_pk>/oopsy/<int:pk>/delete/', OopsyDelete.as_view(), name='oopsy-delete'),
    path('child/<int:child_pk>/oopsy/<int:pk>/edit/', OopsyUpdate.as_view(), name='oopsy-update'),
    path('user/<int:pk>/edit/', UserUpdate.as_view(), name="user-update"),
]

core/models.py
# from django.db import models

# Create your models here.

core/views.py
from django.views.generic import TemplateView

# Create your views here.


class HomePage(TemplateView):

    template_name = "core/index.html"

core/templates/core/base.html
<!DOCTYPE html>
{% load compile_static %}
{% load static %}
<html lang="en">
<head>
    {% include 'core/load_fonts.html' %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description"
          content="B.Nice - share family chores to have more time for fun.">
    <title>B.Nice</title>
    <link rel="stylesheet" href="{% static 'core/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'scss/main.scss'|compile %}"/>
    <link rel="stylesheet" href="{% static 'core/fontawesome-all.css' %}"/>
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'core/site_icon/apple-touch-icon.png' %}"/>
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'core/site_icon/favicon-32x32.png' %}"/>
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'core/site_icon/favicon-16x16.png' %}"/>
    <link rel="manifest" href="{% static 'core/site_icon/site.webmanifest' %}"/>
    <link rel="mask-icon" href="{% static 'core/site_icon/safari-pinned-tab.svg' %}" color="#5bbad5"/>
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'core/site_icon/favicon.ico' %}"/>
    <meta name="apple-mobile-web-app-title" content="B.Nice"/>
    <meta name="application-name" content="B.Nice">
    <meta name="msapplication-TileColor" content="#f8f8f8">
    <meta name="msapplication-config" content="{% static 'core/site_icon/browserconfig.xml' %}">
    <meta name="theme-color" content="#f8f8f8">
</head>
<body class="d-flex flex-column">
<a href="#" id="toTopButton"><i class="fas fa-angle-up"></i></a>
<nav class="navigation navbar navbar-expand-md navbar-dark fixed-top">
        <a class="navigation__brand-link navbar-brand" href="{% url 'core:home' %}">
            <img class="navigation__brand-img"
                 src="{% static 'core/images/logo/Bnice_logo_1744x484px.png' %}"
                 alt="Be Nice Logo">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse"
                data-target="#navbarToggler"
                aria-controls="navbarToggler" aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navigation__icon navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarToggler">
            <ul class="navbar-nav ml-auto mt-2 mt-lg-0">

                {% if request.path == "/" %}
                    <li class="nav-item">
                        <a class="navigation__link nav-link" href="#services">Services</a>
                    </li>
                    <li class="nav-item">
                        <a class="navigation__link nav-link" href="#opinions">Opinions</a>
                    </li>
                    <li class="nav-item">
                        <a class="navigation__link nav-link"
                           href="#about">About</a>
                    </li>
{#                    Placeholder for CONTACT section. #}
{#                    <li class="nav-item">#}
{#                        <a class="navigation__link nav-link" href="#contact">Contact</a>#}
{#                    </li>#}
                {% endif %}
                {% if user.is_authenticated %}
{#                    Content to be displayed on small screens in the navbar #}
                        <li class="nav-item d-md-none">
                            <a class="navigation__link nav-link"
                               href="{% url 'dashboard:dashboard' %}">Dashboard</a>
                        </li>
                    <li class="nav-item d-md-none">
                        <a class="navigation__link nav-link" href="{% url 'accounts:logout' %}">Log Out</a>
                    </li>
{#                    Content to be displayed only on large screens in dropdown menu #}
                    <li class="nav-item dropdown d-none d-md-block">
                        <a class="nav-link dropdown-toggle" href=""
                           id="navbarDropdown" role="button"
                           data-toggle="dropdown" aria-haspopup="true"
                           aria-expanded="false">
                            <i class="navigation__icon fas fa-user"></i>
                        </a>
                        <div class="dropdown-menu"
                             aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="{% url 'dashboard:dashboard' %}">Dashboard</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{% url 'accounts:logout' %}">Log Out</a>
                        </div>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="navigation__link nav-link" href="{% url 'accounts:login' %}">Log In</a>
                    </li>
                    <li class="nav-item">
                        <a class="navigation__link nav-link" href="{% url 'accounts:signup' %}">Sign Up</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </nav>
    <main class="flex-fill">
        {% block content %}
        {% endblock %}
    </main>
    <footer class="footer">
        <div class="container-fluid">
            <div class="row">
                <div class="footer__brand-row col-12 text-center">
                    <a class=""
                       href="{% url 'core:home' %}">
                        <img class="footer__brand-img"
                             src="{% static 'core/images/logo/Bnice_logo_1744x484px.png' %}"
                             alt="Be Nice Logo">
                    </a>
                </div>
            </div>
            <div class="footer__copy-row row text-center">
                <div class="col-md-4">
                    <p class="footer__text">
                        ©
                        <script>document.write(new Date().getFullYear())</script>
                        B.Nice
                    </p>
                </div>
                <div class="col-md-4">
                    <p class="footer__text">
                        Powered by
                        <a href="https://www.djangoproject.com/">
                            <img class="footer__logo" src="{% static 'core/images/footer/django_logo.png' %}">
                        </a>
                    </p>
                </div>
                <div class="col-md-4">
                    <p class="footer__text">
                        Created by
                        <a class="footer__link" href="http://tomasz-kluczkowski.com/">Tomasz Kluczkowski</a>
                    </p>
                </div>
            </div>
        </div>
    </footer>
    <script src="{% static 'core/js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'core/js/popper.min.js' %}"></script>
    <script src="{% static 'core/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'core/js/site.js' %}"></script>
</body>
</html>

core/templates/core/form.html
{% load bootstrap4 %}
<div class="form-container container">
    <div class="row">
        <div class="col-md-12">
            <h1 class="form__section-title">{{ title }}</h1>
        </div>
        <div class="col-md-12">
            {% bootstrap_messages %}
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {% bootstrap_form form layout="horizontal" size="small" label_class="form-label col-md-3" %}
                {% if child_form %}
                    {% bootstrap_form child_form layout="horizontal" size="small" label_class="form-label col-md-3" %}
                {% endif %}
                {% if form.non_field_errors and request.path == "/accounts/login/" %}
                    <div class="invalid-feedback d-block">The username and password do not match.</div>
                {% endif %}
                <div class="row">
                    <div class="col-12 text-center">
                        {% buttons %}
                            <button type="submit" class="form-button btn btn-success">
{#                                {{ title }}#}
                                Submit
                            </button>
                        {% endbuttons %}
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

core/templates/core/index.html
{% extends "core/base.html" %}
{% load static %}
{% block content %}
    <section class="hero">
        <div class="hero-image-container container-fluid px-0">
            <div class="row mx-0">
                <div class="col-12 px-0">
                    <picture>
                        <source srcset="{% static 'core/images/hero/family_480x270px.jpg' %} 480w,
                                        {% static 'core/images/hero/family_960x480px.jpg' %} 960w,
                                        {% static 'core/images/hero/family_1334x750px.jpg' %} 1334w,
                                        {% static 'core/images/hero/family_1920x1080px.jpg' %} 1920w,
                                        {% static 'core/images/hero/family_3840x2160px.jpg' %} 3840w"
                                media="(orientation: landscape)"
                                sizes="100vw">
                        <source srcset="{% static 'core/images/hero/family_750x1334px.jpg' %} 750w,
                                        {% static 'core/images/hero/family_1080x1920px.jpg' %} 1080w"
                                media="(orientation: portrait)"
                                sizes="100vw">
                        <img class="hero-image"
                             src="{% static 'core/images/hero/family_1920x1080px.jpg' %}"
                             alt="Be Nice Hero Image">
                    </picture>
                </div>
            </div>
            <div class="hero__title-container text-center row mx-0">
                <div class="col-md-12">
                    <img class="hero__site-logo"
                         srcset="{% static 'core/images/logo/Bnice_logo_218x61px.png' %} 218w,
                                 {% static 'core/images/logo/Bnice_logo_436x121px.png' %} 436w,
                                 {% static 'core/images/logo/Bnice_logo_872x242px.png' %} 872w,
                                 {% static 'core/images/logo/Bnice_logo_1744x484px.png' %} 1744w"
                         sizes="100vw"
                         src="{% static 'core/images/logo/Bnice_logo_872x242px.png' %}"
                         alt="Be Nice Main Logo">
                    <h2 class="hero__page-title">More You, Less Chores</h2>
                    {% if not user.is_authenticated %}
                        <a href="{% url 'accounts:signup' %}" class="hero__button btn btn-outline-success">Sign Up!</a>
                    {%  endif %}
                </div>
            </div>
        </div>
    </section>
    <section id="services" class="services">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <h2 class="services__section-title">How it Works</h2>
                </div>
            </div>
            <div class="row">
                <div class="col-12">
                    <div class="card-deck">
                        <div class="services__card card">
                            <div class="services__card-header">1</div>
                            <img class="services__card-img card-img-top"
                                 srcset="{% static 'core/images/services/family_with_laptop_177x118px.jpg' %} 177w,
                                         {% static 'core/images/services/family_with_laptop_355x237px.jpg' %} 355w,
                                         {% static 'core/images/services/family_with_laptop_771x514px.jpg' %} 771w"
                                 src="{% static 'core/images/services/family_with_laptop_771x514px.jpg' %}"
                                 sizes=""
                                 alt="Family Sharing Laptop">
                            <div class="card-body">
                                <h5 class="services__card-title card-title">Sign Up</h5>
                                <p class="services__card-text card-text">Register for free and start using our services.</p>
                            </div>
                        </div>
                        <div class="card">
                            <div class="services__card-header">2</div>
                            <img class="card-img-top"
                                 srcset="{% static 'core/images/services/doing_chores_177x118px.jpg' %} 177w,
                                         {% static 'core/images/services/doing_chores_355x237px.jpg' %} 355w,
                                         {% static 'core/images/services/doing_chores_771x514px.jpg' %} 771w"
                                 src="{% static 'core/images/services/doing_chores_771x514px.jpg' %}"
                                 sizes=""
                                 alt="Mum and daughter doing chores together">
                            <div class="card-body">
                                <h5 class="services__card-title card-title">Motivate</h5>
                                <p class="services__card-text card-text">Add tasks to family members and ask them to help you. Agree on the prize they get on completion.</p>
                            </div>
                        </div>
                        <div class="card">
                            <div class="services__card-header">3</div>
                            <img class="card-img-top"
                                 srcset="{% static 'core/images/services/boy_with_a_toy_plane_177x118px.jpg' %} 177w,
                                         {% static 'core/images/services/boy_with_a_toy_plane_355x237px.jpg' %} 355w,
                                         {% static 'core/images/services/boy_with_a_toy_plane_771x514px.jpg' %} 771w"
                                 src="{% static 'core/images/services/boy_with_a_toy_plane_771x514px.jpg' %}"
                                 sizes=""
                                 alt="Rewarding your child">
                            <div class="card-body">
                                <h5 class="services__card-title card-title">Reward</h5>
                                <p class="services__card-text card-text">Positive reinforcement is best. Make them feel happy by seeing your smile.</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <section id="opinions" class="testimonials">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <h2 class="testimonials__section-title">User's Opinions</h2>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <img class="testimonials__img img-fluid rounded" src="{% static 'core/images/testimonials/man_hugging_daugther_540x360px.jpg' %}">
                </div>
                <div class="col-md-6">
                    <h2 class="testimonials__title">What Is Great About B.Nice</h2>
                    <cite class="testimonials__cite">
                        "My child was only 6 when we started to use B.Nice.
                        We struggled maintaining routine and sometimes she would help us out and other times she would blatantly refuse or ignore us.
                        With a system introduced now she knows that nothing is for free and enjoys supporting us."
                    </cite>
                    <h3 class="testimonials__username">Tom, London, UK</h3>
                </div>
            </div>
            <div class="row mt-5">
                <div class="col-md-6 order-lg-1">
                    <h2 class="testimonials__title">Why I keep using B.Nice</h2>
                    <cite class="testimonials__cite">
                        "I barely had any time for myself, there was always so much work at home. I tried many times asking my child for help but it never worked in the long run. Since I started using B.Nice we finally have spare time and can enjoy each others company and go out."
                    </cite>
                    <h3 class="testimonials__username">Violet, London, UK</h3>
                </div>
                <div class="col-md-6 order-lg-2">
                    <img class="testimonials__img img-fluid rounded" src="{% static 'core/images/testimonials/woman_whispering_to_child_540x360px.jpg' %}">
                </div>
            </div>
        </div>
    </section>
    <section id="about" class="about">
        <div class="container-fluid px-0">
            <div class="row mx-0">
                <div class="about__img-container col-12 px-0">
                    <img class="img-fluid" src="{% static 'core/images/about/girl_playing_on_grass_3840x950px.jpg' %}">
                </div>
            </div>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-12">
                        <h2 class="about__section-title">About Us</h2>
                        <p class="about__paragraph">
                            Natalie was 6 year old when I realised I am going round in circles trying to teach her
                            how to be a good person.
                            It all starts at home and the earlier you start the
                            better.
                            Easier said than done.<br><br>
                            I started from making a wall chart with her good and
                            bad deeds listed with smileys and sad face
                            icons.
                            We have noticed straight away with my wife a positive change in our child's behaviour
                            and an idea of a website helping us to keep track of it all dawned on me.<br><br>
                            That's how B.Nice started - out of a simple need to
                            bring more happiness to our family.
                        </p>
                </div>
            </div>
        </div>
    </section>
{#    <section id="contact" class="contact">#}
{#        <div class="container">#}
{#            <div class="row">#}
{#                <div class="col-12">#}
{#                    <h2 class="contact__section-title">Contact</h2>#}
{#                    <p>Here django auto generated contact form to be injected</p>#}
{#                </div>#}
{#            </div>#}
{#        </div>#}
{#    </section>#}
{% endblock %}

core/templates/core/load_fonts.html
{% load static %}
<style>
/*Declare all local fonts */

/* Cabin sketch font */
/* latin */
@font-face {
  font-family: 'Cabin Sketch';
  font-style: normal;
  font-weight: 400;
  src: url("{% static 'core/fonts/cabin_sketch.woff2' %}") format('woff2');
  unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD;
}

/* Lato font */
/* latin-ext */
@font-face {
  font-family: 'Lato';
  font-style: normal;
  font-weight: 300;
  src: url("{% static 'core/fonts/lato_latin_ext.woff2' %}") format('woff2');
  unicode-range: U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF;
}
/* latin */
@font-face {
  font-family: 'Lato';
  font-style: normal;
  font-weight: 300;
  src: url("{% static 'core/fonts/lato_latin.woff2' %}") format('woff2');
  unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD;
}

/* Raleway font */
/* latin-ext */
@font-face {
  font-family: 'Raleway';
  font-style: normal;
  font-weight: 400;
  src: url("{% static 'core/fonts/raleway_latin_ext.woff2' %}") format('woff2');
  unicode-range: U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF;
}
/* latin */
@font-face {
  font-family: 'Raleway';
  font-style: normal;
  font-weight: 400;
  src: url("{% static 'core/fonts/raleway_latin.woff2' %}") format('woff2');
  unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD;
}
</style>

core/templates/core/login_form.html
{% load bootstrap4 %}
<div class="form-container container">
    <div class="row">
        <div class="col-md-12">
            <h1 class="form__section-title">{{ title }}</h1>
        </div>
        <div class="col-md-12">
            {% bootstrap_messages %}
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {% bootstrap_form form layout="horizontal" size="small" label_class="form-label col-md-3" %}
                {% if child_form %}
                    {% bootstrap_form child_form layout="horizontal" size="small" label_class="form-label col-md-3" %}
                {% endif %}
                {% if form.non_field_errors and request.path == "/accounts/login/" %}
                    <div class="invalid-feedback d-block">The username and password do not match.</div>
                {% endif %}
                <p>Not registered yet? <a class="dark-link" href="{% url 'accounts:signup' %}">Sign up here!</a></p>
                <div class="row">
                    <div class="col-12 text-center">
                        {% buttons %}
                            <button type="submit" class="form-button btn btn-success">
{#                                {{ title }}#}
                                Submit
                            </button>
                        {% endbuttons %}
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>