Bnice/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace="core")),
    path('accounts/', include('accounts.urls', namespace="accounts")),
    path('dashboard/', include('dashboard.urls', namespace="dashboard")),
]

if settings.DEBUG:  # pragma: no cover
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

if settings.DEBUG:  # pragma: no cover
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

core/urls.py
from django.urls import path
from core.views import HomePage

app_name = "core"


urlpatterns = [
    path('', HomePage.as_view(), name="home")
]

dashboard/urls.py
from django.urls import path
from dashboard.views import (
    DashboardPage, CreateChildPage, ChildDetail,
    AddSmiley, AddOopsy, UserUpdate, ChildUpdate, ChildDelete,
    SmileyDelete, OopsyDelete, SmileyUpdate, OopsyUpdate)

app_name = "dashboard"

urlpatterns = [
    path('', DashboardPage.as_view(), name="dashboard"),
    path('child/<int:pk>/', ChildDetail.as_view(), name="child-detail"),
    path('child/new/', CreateChildPage.as_view(), name="child-create"),
    path('child/<int:pk>/edit/', ChildUpdate.as_view(), name="child-update"),
    path('child/<int:pk>/delete/', ChildDelete.as_view(), name='child-delete'),
    path('child/<int:pk>/smiley/new/', AddSmiley.as_view(), name="smiley-create"),
    path('child/<int:child_pk>/smiley/<int:pk>/delete/', SmileyDelete.as_view(), name='smiley-delete'),
    path('child/<int:child_pk>/smiley/<int:pk>/edit/', SmileyUpdate.as_view(), name='smiley-update'),
    path('child/<int:pk>/oopsy/new/', AddOopsy.as_view(), name="oopsy-create"),
    path('child/<int:child_pk>/oopsy/<int:pk>/delete/', OopsyDelete.as_view(), name='oopsy-delete'),
    path('child/<int:child_pk>/oopsy/<int:pk>/edit/', OopsyUpdate.as_view(), name='oopsy-update'),
    path('user/<int:pk>/edit/', UserUpdate.as_view(), name="user-update"),
]

dashboard/models.py
from django.db import models
from django.urls import reverse
from accounts.models import Child


# Create your models here.
class Action(models.Model):
    """Saves actions.

    This model will save child's actions for which they earn points.
    Claimed field will be set to True when child reaches enough points to
    get a star. This field is intended to never be shown to the user.
    """
    earned_on = models.DateTimeField(blank=False)
    claimed = models.BooleanField(default=False)
    points_remaining = models.PositiveSmallIntegerField(default=0)
    description = models.CharField(max_length=255, blank=False)
    points = models.IntegerField(default=3, blank=False)

    class Meta:
        abstract = True
        ordering = ['earned_on']

    def get_absolute_url(self):
        return reverse("dashboard:child-detail", kwargs={"pk": self.owner.pk})

    def __str__(self):
        return self.description


class Smiley(Action):
    owner = models.ForeignKey(Child, on_delete=models.CASCADE, related_name='smileys')
    star_awarded = models.BooleanField(default=False)

    class Meta:
        permissions = (
            ('view_smiley_instance', 'View Smiley Instance'),
            ('add_smiley_instance', 'Add Smiley Instance'),
            ('edit_smiley_instance', 'Edit Smiley Instance'),
            ('delete_smiley_instance', 'Delete Smiley Instance')
        )


class Oopsy(Action):
    owner = models.ForeignKey(Child, on_delete=models.CASCADE, related_name='oopsies')

    class Meta:
        permissions = (
            ('view_oopsy_instance', 'View Oopsy Instance'),
            ('add_oopsy_instance', 'Add Oopsy Instance'),
            ('edit_oopsy_instance', 'Edit Oopsy Instance'),
            ('delete_oopsy_instance', 'Delete Oopsy Instance')
        )

dashboard/forms.py
from django import forms
from dashboard.models import Smiley, Oopsy

base_smileys = [
    'Add new',
    'Folded washing',
    'Cleaned bathroom',
    'Mopped floor',
    'Removed cutlery from dishwasher'
]

base_oopsies = [
    'Add new',
    'Was lying',
    'Left mess',
    'Talked back to parent',
    "Didn't do homework",
]


class AddActionForm(forms.ModelForm):
    # This field will be hidden and only shown if user selects 'Add new' in the
    # dropdown menu - then it will be set to required in jquery.
    new_description = forms.CharField(max_length=255, required=False)
    new_description.help_text = "Required, Create a new description"

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    def clean(self):
        super().clean()
        # If user has given a new description for the action it will overwrite
        # whatever was selected in the dropdown menu.
        new_description = self.cleaned_data.get("new_description")

        if new_description:
            self.cleaned_data['description'] = new_description
        return self.cleaned_data

    def set_description(self, model, initial_choice_list):
        """Set 'description' field to forms.ChoiceField.

        Create a list of distinct descriptions for actions using appropriate to the model base list and add that to
        options in select html element when rendered in the form.

        Parameters
        ----------
        model : Action
            Subclass of Action model (Smiley or Oopsy).
        initial_choice_list : list(str)
            List of strings describing action to show in the dropdown menu.

        Returns
        -------
            None
        """
        choices = list(model.objects.order_by("description").values_list("description", flat=True).distinct())
        distinct_choices = initial_choice_list + [choice for choice in choices if choice not in initial_choice_list]
        self.fields['description'] = forms.ChoiceField(choices=[(choice, choice) for choice in distinct_choices])
        self.fields['description'].help_text = "Required"

    class Meta:
        fields = ("description", "new_description", "points")


class AddSmileyForm(AddActionForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.set_description(Smiley, base_smileys)

    class Meta(AddActionForm.Meta):
        model = Smiley
        help_texts = {"points": "Required, How much was this task worth?"}


class AddOopsyForm(AddActionForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.set_description(Oopsy, base_oopsies)

    class Meta(AddActionForm.Meta):
        model = Oopsy
        help_texts = {"points": "Required, How many points to take away?"}

dashboard/views.py
from django.db import transaction
from django.shortcuts import get_object_or_404
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.urls import reverse, reverse_lazy
from django.utils import timezone
from django.http import HttpResponseRedirect

from accounts.models import Child, User
from accounts.forms import ChildCreateForm, ChildUpdateForm, UserUpdateForm
from core.mixins.permission_mixins import (PermissionRequired403Mixin, PermissionRequiredSetChild403Mixin,
                                           PermissionRequired403GlobalMixin)
from dashboard.models import Smiley, Oopsy
from dashboard.forms import AddSmileyForm, AddOopsyForm
from dashboard.services import StarAwarding


class DashboardPage(ListView):
    model = Child
    template_name = "dashboard/dashboard.html"

    def get_queryset(self):
        if self.request.user.is_child():
            return Child.objects.filter(pk=self.request.user.pk).select_related('parent', 'user')
        else:
            return Child.objects.filter(parent=self.request.user).select_related('parent', 'user')


class CreateChildPage(PermissionRequired403GlobalMixin, CreateView):
    model = Child
    template_name = "dashboard/add_child.html"
    form_class = ChildCreateForm
    success_url = reverse_lazy('dashboard:dashboard')
    permission_required = 'accounts.add_child_instance'

    def get_initial(self):
        self.initial.update({"current_user": self.request.user})
        return self.initial


class ChildDetail(PermissionRequired403Mixin, DetailView):
    """Awards stars before displaying Child details."""
    model = Child
    template_name = "dashboard/child_detail.html"
    permission_required = 'accounts.view_child_instance'

    def get_context_data(self, **kwargs):
        child = self.get_object()
        kwargs['smileys'] = child.smileys.all()
        kwargs['oopsies'] = child.oopsies.all()
        star_awarding = StarAwarding(kwargs['smileys'], kwargs['oopsies'], child.star_points)
        star_awarding.award_star()
        return super().get_context_data(**kwargs)


class AddAction(PermissionRequiredSetChild403Mixin, CreateView):
    permission_required = 'accounts.edit_child_instance'

    def dispatch(self, request, *args, **kwargs):
        self.child = get_object_or_404(Child.objects, pk=self.kwargs['pk'])
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        form.instance = form.save(commit=False)
        form.instance.owner = self.child
        form.instance.earned_on = timezone.now()
        form.save()
        return super().form_valid(form)


class AddSmiley(AddAction):
    model = Smiley
    template_name = "dashboard/add_action.html"
    form_class = AddSmileyForm


class AddOopsy(AddAction):
    model = Oopsy
    template_name = "dashboard/add_action.html"
    form_class = AddOopsyForm


class UserUpdate(PermissionRequired403Mixin, UpdateView):
    model = User
    form_class = UserUpdateForm
    template_name = 'dashboard/user_update.html'
    success_url = reverse_lazy('dashboard:dashboard')
    permission_required = 'accounts.edit_user_instance'


class ChildUpdate(PermissionRequiredSetChild403Mixin, UpdateView):
    model = User
    form_class = UserUpdateForm
    child_form_class = ChildUpdateForm
    template_name = 'dashboard/child_update.html'
    permission_required = 'accounts.edit_child_instance'

    def dispatch(self, request, *args, **kwargs):
        self.child = get_object_or_404(Child.objects.select_related('parent'), user__pk=self.kwargs['pk'])
        return super().dispatch(request, *args, **kwargs)

    def get_success_url(self, **kwargs):
        return reverse_lazy('dashboard:child-detail', **kwargs)

    def get_context_data(self, **kwargs):
        kwargs['child_form'] = self.child_form_class(initial={'star_points': self.child.star_points})
        return super().get_context_data(**kwargs)

    @transaction.atomic
    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        user_form = self.form_class(request.POST, request.FILES, instance=self.object)
        child_form = self.child_form_class(request.POST, instance=self.child)
        if user_form.is_valid() and child_form.is_valid():
            user_data = user_form.save(commit=False)
            user_data.save()
            child_data = child_form.save(commit=False)
            child_data.save()
            return HttpResponseRedirect(self.get_success_url(kwargs={'pk': self.child.user.pk}))
        else:
            return self.render_to_response(self.get_context_data(form=user_form, child_form=child_form))


class ChildDelete(PermissionRequired403Mixin, DeleteView):
    model = Child
    success_url = reverse_lazy('dashboard:dashboard')
    template_name = 'dashboard/child_delete.html'
    permission_required = 'accounts.delete_child_instance'


class ActionDeleteBase(PermissionRequired403Mixin, DeleteView):
    """Base class for deleting actions. Not to be used on its own."""
    model = None

    def get_queryset(self):
        qs = self.model.objects.filter(pk=self.kwargs.get('pk')).select_related('owner', 'owner__user', 'owner__parent')
        return qs

    def get_context_data(self, **kwargs):
        action = self.object
        kwargs['child'] = action.owner
        return super().get_context_data(**kwargs)

    def get_success_url(self):
        action = self.object
        child = action.owner
        return reverse('dashboard:child-detail', kwargs={'pk': child.pk})


class SmileyDelete(ActionDeleteBase):
    """Delete smiley actions."""
    model = Smiley
    template_name = 'dashboard/smiley_delete.html'
    permission_required = 'dashboard.delete_smiley_instance'


class OopsyDelete(ActionDeleteBase):
    """Delete oopsy actions."""
    model = Oopsy
    template_name = 'dashboard/oopsy_delete.html'
    permission_required = 'dashboard.delete_oopsy_instance'


class ActionUpdateBase(PermissionRequired403Mixin, UpdateView):
    """Base class for updating unclaimed smiley and oopsy objects. Do not use on its own."""
    model = None
    fields = ('description', 'points')

    def get_context_data(self, **kwargs):
        action = self.object
        kwargs['child'] = action.owner
        return super().get_context_data(**kwargs)

    def get_success_url(self):
        action = self.object
        child = action.owner
        return reverse('dashboard:child-detail', kwargs={'pk': child.pk})


class SmileyUpdate(ActionUpdateBase):
    model = Smiley
    template_name = 'dashboard/smiley_update.html'
    permission_required = 'dashboard.edit_smiley_instance'


class OopsyUpdate(ActionUpdateBase):
    model = Oopsy
    template_name = 'dashboard/oopsy_update.html'
    permission_required = 'dashboard.edit_oopsy_instance'

dashboard/templates/dashboard/_action_list.html
{% load dashboard_tags %}
<div class="dashboard__actions-box col-md-6">
    {% set_var "" as current_date %}
    <ul class="list-group">
        {% for action in actions reversed %}
            {% if current_date != action.earned_on|date:"j M Y" %}
                <li class="dashboard__action-date-wrapper list-group-item  d-flex justify-content-between align-items-center">
                    <p class="dashboard__action-date">
                        <i class="far fa-calendar-alt"></i>
                        {{ action.earned_on|date:"j M Y" }}
                    </p>
                    {% if forloop.first %}
                        {% if action|get_model_name == "Smiley" %}
                            {% set_var "earned" as points_status %}
                            {% set_var "success" as badge_color %}
                        {% else %}
                            {% set_var "lost" as points_status %}
                            {% set_var "danger" as badge_color %}
                        {% endif %}
                        <p class="dashboard__action-date">Points {{ points_status }}</p>
                    {% endif %}
                </li>
            {% endif %}
            {% if action.claimed %}
                {% set_var "dashboard__action-claimed" as action_status %}
            {% else %}
                {% set_var "" as action_status %}
            {% endif %}
            <li class="dashboard__list-group-description {{ action_status }} list-group-item d-flex justify-content-between align-items-center">
                <p class="dashboard__action-description">
                    {{ action.description }}
                </p>
                <div>
                {#            Allow updating/deleting of actions if not claimed #}
                {% if user.is_administrator or user.is_parent %}
                    {% if not action.claimed %}
                        <a class="btn btn-danger form-button-min"
                        {% if action|get_model_name == "Smiley" %}
                           href="{% url 'dashboard:smiley-delete' pk=action.pk child_pk=child.pk %}">
                        {% else %}
                           href="{% url 'dashboard:oopsy-delete' pk=action.pk child_pk=child.pk %}">
                        {% endif %}
                            <i class="fas fa-trash-alt"></i>
                        </a>
                        <a class="btn btn-warning form-button-min"
                        {% if action|get_model_name == "Smiley" %}
                           href="{% url 'dashboard:smiley-update' pk=action.pk child_pk=child.pk %}">
                        {% else %}
                           href="{% url 'dashboard:oopsy-update' pk=action.pk child_pk=child.pk %}">
                        {% endif %}
                            <i class="far fa-edit"></i>
                        </a>
                    {% endif %}
                {% endif %}
                    <span class="badge badge-{{ badge_color }} badge-pill">
                        {{ action.points }}
                    </span>
                </div>
            </li>
            {% if action.star_awarded %}
                <li class="dashboard__list-group-description dashboard__star-awarded list-group-item d-flex justify-content-between align-items-center">
                    You have earned a star!
                    <i class="dashboard__star fas fa-star"></i>
                </li>
            {% endif %}
            {% if action.points_remaining > 0 %}
                <li class="dashboard__list-group-description list-group-item d-flex justify-content-between align-items-center">
                    <p class="dashboard__action-description">
                        Remaining points
                    </p>
                    <span class="badge badge-{{ badge_color }} badge-pill">{{ action.points_remaining }}</span>
                </li>
            {% endif %}
            {% set_var action.earned_on|date:"j M Y" as current_date %}
        {% endfor %}
    </ul>
</div>

dashboard/templates/dashboard/add_action.html
{% extends "dashboard/dashboard.html" %}
{% load static %}
{% block form %}
    <div class="dashboard__action-form">
        {%  if "oopsy/new/" in request.path %}
            {% include "core/form.html" with title="Add Oopsy" %}
        {% else %}
            {% include "core/form.html" with title="Add Smiley" %}
        {% endif %}
    </div>
{% endblock %}

dashboard/templates/dashboard/add_child.html
{% extends "dashboard/dashboard.html" %}
{% load static %}
{% block form %}
    {% include "core/form.html" with title="Add New Child" %}
{% endblock %}

dashboard/templates/dashboard/child_delete.html
{% extends "dashboard/dashboard.html" %}
{% load static %}
{% block form %}
<div class="row">
    <div class="delete-wrapper col-12">
        <div class="delete-container jumbotron text-center">
            <h1 class="delete-title">Delete Child</h1>
            {% if child.user.profile_photo %}
                <div class="dashboard__card-img-container text-center">
                    <img class="dashboard__profile-photo card-img-top"
                         src="{{ child.user.profile_photo.url }}"
                         alt="Child profile photo">
                </div>
            {% else %}
                <div class="dashboard__card-img-container text-center">
                    <img class="dashboard__profile-photo card-img-top"
                         src="{% static 'dashboard/images/avatar_500x500px.png' %}"
                         alt="Child avatar">
                </div>
            {% endif %}
            <p class="delete-paragraph">Are you sure you want to delete the child:
                <span class="delete-object-name">
                    {{ child.user.name }}?
                </span>
            </p>
            <form action="" method="POST">
              {% csrf_token %}
              <input class="delete-button btn btn-danger" type="submit" action="" value="Yes, delete."/>
            </form>
        </div>
    </div>
</div>
{% endblock %}

dashboard/templates/dashboard/child_detail.html
{% extends "dashboard/child_detail_base.html" %}
{% load static %}
{% block progress %}
    <div class="dashboard__actions-container row">
        <div class="col-md-12">
            <div class="row">
                <div class="col-12">
                    {% if user.is_child %}
                        <h2 class="dashboard__actions-title">Your Progress</h2>
                    {% else %}
                        <h2 class="dashboard__actions-title">{{ child.user.name }}'s Progress</h2>
                    {% endif %}
                    {% if not smileys and not oopsies %}
                        {% if user.is_child %}
                            <p class="dashboard__paragraph">You have no actions added yet. Ask your parent to add them. It would be nice if you asked how you can help!</p>
                        {% else %}
                            <p class="dashboard__paragraph">Your child has no actions added yet. Use the User Panel to add them!</p>
                        {% endif %}
                    {% endif %}
                </div>
            </div>
            <div class="row justify-content-between">
                {% if smileys %}
                    {% include "dashboard/_action_list.html" with actions=smileys %}
                {% endif %}
                {% if oopsies %}
                    {% include "dashboard/_action_list.html" with actions=oopsies %}
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

dashboard/templates/dashboard/child_update.html
{% extends "dashboard/dashboard.html" %}
{% load static %}
{% block form %}
    {% include "core/form.html" with title="Update Child Record" %}
{% endblock %}

dashboard/templates/dashboard/dashboard.html
{% extends "dashboard/dashboard_base.html" %}
{% load static %}
{% block display_panel %}
    <div class="dashboard__display-panel col-sm-8 col-lg-9 col-xl-10 mr-auto">
        {% if request.path == "/dashboard/child/new/" %}
            <div class="row">
                <div class="col-12 my-auto"><div class="alert alert-info alert-dismissible fade show" role="alert">
                        Please fill in your child's account details. They can use it to log in and view their progress.
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                </div>
            </div>
        {% endif %}
        {% block form %}
        {% endblock %}
        {% if child_list %}
            <div class="row">
                {% for child in child_list %}
                    <div class="col-lg-4 col-md-6 d-flex dashboard__card card">
                        <a href="{% url 'dashboard:child-update' pk=child.user.pk %}">
                            {% if child.user.profile_photo %}
                                <div class="dashboard__card-img-container text-center">
                                    <img class="dashboard__profile-photo card-img-top"
                                         src="{{ child.user.profile_photo.url }}"
                                         alt="Child profile photo">
                                </div>
                            {% else %}
                                <div class="dashboard__card-img-container text-center">
                                    <img class="dashboard__profile-photo card-img-top"
                                         src="{% static 'dashboard/images/avatar_500x500px.png' %}"
                                         alt="Child avatar">
                                </div>
                            {% endif %}
                        </a>
                        <div class="card-body p-0">
                            <div class="row">
                                <div class="col-12 text-center">
                                    <a class="dashboard__card-title card-title"
                                       href="{% url 'dashboard:child-detail' pk=child.pk %}">
                                       {{ child.user.name }}
                                    </a>
                                </div>
                            </div>
                        </div>
                        <hr>
                        {%  if user.is_parent %}
                            <div class="row">
                                <div class="col-12 text-center">
                                    <a class="btn btn-danger form-button-small"
                                       href="{% url 'dashboard:child-delete' pk=child.pk %}">
                                            <i class="fas fa-user-slash"></i>
                                    </a>
                                </div>
                            </div>
                        {% endif %}
                    </div>
                {% endfor %}
            </div>
        {% elif request.path == "/dashboard/" %}
            <div class="row">
                <div class="col-12 my-auto">
                    <div class="alert alert-info alert-dismissible fade show" role="alert">
                        You have no children added. Please use "Add Child" option in the User Panel to get started.
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                </div>
            </div>
        {% endif %}
    </div>
{% endblock %}

dashboard/templates/dashboard/dashboard_base.html
{% extends "core/base.html" %}
{% load static %}
{% block content %}
    <section class="dashboard">
        <div class="container-fluid px-0">
            <div class="row dashboard__container">
                <div class="col-12">
                    <div class="row">
                        {% block display_panel %}
                        {% endblock %}
                        <div class="dashboard__user-panel col-sm-4 col-lg-3 col-xl-2">
                            <div class="row">
                                <div class="col-12 text-center">
                                    <a href="{% url 'dashboard:user-update' pk=request.user.pk %}">
                                        {% if request.user.profile_photo %}
                                            <img class="dashboard__profile-photo"
                                                 src="{{ request.user.profile_photo.url }}"
                                                 alt="User Profile Photo">
                                        {% else %}
                                            <img class="dashboard__profile-photo"
                                                 src="{% static 'dashboard/images/avatar_500x500px.png' %}"
                                                 alt="User Profile Photo">
                                        {% endif %}
                                    </a>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-12 text-center">
                                    <h2 class="dashboard__username">
                                        {{ request.user.username }}
                                    </h2>
                                    <h2 class="dashboard__email">
                                        {{ request.user.email }}
                                    </h2>
                                </div>
                            </div>
                            <hr>
                            {% if request.user.is_child %}
                                <div class="row">
                                    <div class="col-3 col-sm-12 text-center">
                                        <a class="btn btn-dark ui-button"
                                           href="{% url 'dashboard:dashboard' %}">
                                            <i class="fas fa-users"></i>
                                        </a>
                                    </div>
                                </div>
                            {% endif %}
                            {% if request.user.is_authenticated and request.user.is_parent or request.user.is_administrator %}
                                <div class="row">
                                    <div class="col-3 col-sm-12 text-center">
                                        <a class="btn btn-dark ui-button"
                                           href="{% url 'dashboard:dashboard' %}">
                                            <i class="fas fa-users"></i>
                                        </a>
                                    </div>

                                    <div class="col-3 col-sm-12 text-center">
                                        <a class="btn btn-dark ui-button"
                                           href="{% url 'dashboard:child-create' %}">
                                            <i class="fas fa-user-plus"></i>
                                        </a>
                                    </div>
                                    {% url 'dashboard:child-detail' pk=child.pk as child_detail_url %}
                                    {% if child_detail_url %}
                                        <div class="col-3 col-sm-12 text-center">
                                            <a class="btn btn-dark ui-button"
                                               href="{% url 'dashboard:smiley-create' pk=child.pk %}">
                                                <i class="fas fa-thumbs-up"></i>
                                            </a>
                                        </div>
                                        <div class="col-3 col-sm-12 text-center">
                                            <a class="btn btn-dark ui-button"
                                               href="{% url 'dashboard:oopsy-create' pk=child.pk %}">
                                                <i class="fas fa-thumbs-down"></i>
                                            </a>
                                        </div>
                                    {% endif %}
                                </div>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

dashboard/templates/dashboard/oopsy_delete.html
{% extends "dashboard/dashboard.html" %}
{% load static %}
{% block form %}
<div class="row">
    <div class="delete-wrapper col-12">
        <div class="delete-container jumbotron text-center">
            <h1 class="delete-title">Delete Oopsy</h1>
            <p class="delete-paragraph">Are you sure you want to delete this action:
                <span class="delete-object-name">
                    {{ oopsy.description }}?
                </span>
            </p>
            <form action="" method="POST">
              {% csrf_token %}
              <input class="delete-button btn btn-danger" type="submit" action="" value="Yes, delete."/>
            </form>
        </div>
    </div>
</div>
{% endblock %}

dashboard/templates/dashboard/oopsy_update.html
{% extends "dashboard/dashboard.html" %}
{% load static %}
{% block form %}
    {% include "core/form.html" with title="Update Oopsy Record" %}
{% endblock %}

dashboard/templates/dashboard/smiley_update.html
{% extends "dashboard/dashboard.html" %}
{% load static %}
{% block form %}
    {% include "core/form.html" with title="Update Smiley Record" %}
{% endblock %}

dashboard/templates/dashboard/user_update.html
{% extends "dashboard/dashboard.html" %}
{% load static %}
{% block form %}
    {% include "core/form.html" with title="Update Your Profile" %}
{% endblock %}